Exit non-zero if the tests fail
Signed-off-by: Stefano Rivera <stefano@rivera.za.net>

diff --git a/t/run_coverage b/t/run_coverage
--- a/t/run_coverage
+++ b/t/run_coverage
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+set -eu
+
 orig_dir=$(cd $(dirname $0) && pwd -P)
 tmpdir=$(mktemp -d)
 
@@ -17,7 +19,11 @@ EOF
 export COVERAGE_PROCESS_START=$tmpdir/.coveragerc
 export PYTHONPATH=$tmpdir:
 
+# Produce a coverage report, even if the tests fail
+set +e
 $orig_dir/run_tests
+exitcode=$?
+set -e
 
 cd $tmpdir
 coverage3 combine
@@ -25,3 +31,5 @@ coverage3 html -d $orig_dir/report
 coverage3 report -m
 cd $orig_dir
 rm -rf $tmpdir
+
+exit $exitcode
